name: Caramel
version: '${project.version}'
main: dev.klash.caramel.Caramel
api-version: '1.21'
folia-supported: true
commands:
  caramel:
    description: "Caramel's default command"
permissions:
  caramel.commands.base:
    default: 'op'
    description: "Allows caramel's base command"