name: Deploy Javadoc (legacy)

on:
 push:
    branches:
      - none_dont_push_any
#      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # if you have a protection rule on your repository, you'll need to give write permission to the workflow.
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
          distribution: temurin
      - name: Create branch for Javadoc
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          java-version: 17
          javadoc-branch: javadoc
          target-folder: docs/javadoc
          project: maven
